# moteur.ma

## https://www.moteur.ma/fr/neuf/fiche-technique-prix/

In [10]:
import json
from urllib.request import urlopen,Request
from bs4 import BeautifulSoup
import ssl
import urllib
import re

def extract_url(url):
    
    # Ignore SSL certificate errors
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})

    html = urlopen(req, context=ctx).read()
    soup = BeautifulSoup(html, "html.parser")

    links = soup.find_all('div', class_='content-inner')
    
    data_list=[]
    for link in links:
        if link.find('div', class_='price color_primary PriceListing'):
            a=link.find('a')
            data=a['href']
            data_list.append(data)
    return data_list

In [11]:
url='https://www.moteur.ma/fr/voiture/achat-voiture-occasion/'
results=extract_url(url)
for i in range(30, 27841, 30):
    results.extend(extract_url(url+str(i)))
    print(i)

30
60
90
120
150
180
210
240
270
300
330
360
390
420
450
480
510
540
570
600
630
660
690
720
750
780
810
840
870
900
930
960
990
1020
1050
1080
1110
1140
1170
1200
1230
1260
1290
1320
1350
1380
1410
1440
1470
1500
1530
1560
1590
1620
1650
1680
1710
1740
1770
1800
1830
1860
1890
1920
1950
1980
2010
2040
2070
2100
2130
2160
2190
2220
2250
2280
2310
2340
2370
2400
2430
2460
2490
2520
2550
2580
2610
2640
2670
2700
2730
2760
2790
2820
2850
2880
2910
2940
2970
3000
3030
3060
3090
3120
3150
3180
3210
3240
3270
3300
3330
3360
3390
3420
3450
3480
3510
3540
3570
3600
3630
3660
3690
3720
3750
3780
3810
3840
3870
3900
3930
3960
3990
4020
4050
4080
4110
4140
4170
4200
4230
4260
4290
4320
4350
4380
4410
4440
4470
4500
4530
4560
4590
4620
4650
4680
4710
4740
4770
4800
4830
4860
4890
4920
4950
4980
5010
5040
5070
5100
5130
5160
5190
5220
5250
5280
5310
5340
5370
5400
5430
5460
5490
5520
5550
5580
5610
5640
5670
5700
5730
5760
5790
5820
5850
5880
5910
5940
5970
6000
6030
6060
6090
6120
6150
6180
6210
6240
6270
6300
6330
6360
6390
6420
6450
6480
6510
6540
6570
6600
6630
6660
6690
6720
6750
6780
6810
6840
6870
6900
6930
6960
6990
7020
7050
7080
7110
7140
7170
7200
7230
7260
7290
7320
7350
7380
7410
7440
7470
7500
7530
7560
7590
7620
7650
7680
7710
7740
7770
7800
7830
7860
7890
7920
7950
7980
8010
8040
8070
8100
8130
8160
8190
8220
8250
8280
8310
8340
8370
8400
8430
8460
8490
8520
8550
8580
8610
8640
8670
8700
8730
8760
8790
8820
8850
8880
8910
8940
8970
9000
9030
9060
9090
9120
9150
9180
9210
9240
9270
9300
9330
9360
9390
9420
9450
9480
9510
9540
9570
9600
9630
9660
9690
9720
9750
9780
9810
9840
9870
9900
9930
9960
9990
10020
10050
10080
10110
10140
10170
10200
10230
10260
10290
10320
10350
10380
10410
10440
10470
10500
10530
10560
10590
10620
10650
10680
10710
10740
10770
10800
10830
10860
10890
10920
10950
10980
11010
11040
11070
11100
11130
11160
11190
11220
11250
11280
11310
11340
11370
11400
11430
11460
11490
11520
11550
11580
11610
11640
11670
11700
11730
11760
11790
11820
11850
11880
11910
11940
11970
12000
12030
12060
12090
12120
12150
12180
12210
12240
12270
12300
12330
12360
12390
12420
12450
12480
12510
12540
12570
12600
12630
12660
12690
12720
12750
12780
12810
12840
12870
12900
12930
12960
12990
13020
13050
13080
13110
13140
13170
13200
13230
13260
13290
13320
13350
13380
13410
13440
13470
13500
13530
13560
13590
13620
13650
13680
13710
13740
13770
13800
13830
13860
13890
13920
13950
13980
14010
14040
14070
14100
14130
14160
14190
14220
14250
14280
14310
14340
14370
14400
14430
14460
14490
14520
14550
14580
14610
14640
14670
14700
14730
14760
14790
14820
14850
14880
14910
14940
14970
15000
15030
15060
15090
15120
15150
15180
15210
15240
15270
15300
15330
15360
15390
15420
15450
15480
15510
15540
15570
15600
15630
15660
15690
15720
15750
15780
15810
15840
15870
15900
15930
15960
15990
16020
16050
16080
16110
16140
16170
16200
16230
16260
16290
16320
16350
16380
16410
16440
16470
16500
16530
16560
16590
16620
16650
16680
16710
16740
16770
16800
16830
16860
16890
16920
16950
16980
17010
17040
17070
17100
17130
17160
17190
17220
17250
17280
17310
17340
17370
17400
17430
17460
17490
17520
17550
17580
17610
17640
17670
17700
17730
17760
17790
17820
17850
17880
17910
17940
17970
18000
18030
18060
18090
18120
18150
18180
18210
18240
18270
18300
18330
18360
18390
18420
18450
18480
18510
18540
18570
18600
18630
18660
18690
18720
18750
18780
18810
18840
18870
18900
18930
18960
18990
19020
19050
19080
19110
19140
19170
19200
19230
19260
19290
19320
19350
19380
19410
19440
19470
19500
19530
19560
19590
19620
19650
19680
19710
19740
19770
19800
19830
19860
19890
19920
19950
19980
20010
20040
20070
20100
20130
20160
20190
20220
20250
20280
20310
20340
20370
20400
20430
20460
20490
20520
20550
20580
20610
20640
20670
20700
20730
20760
20790
20820
20850
20880
20910
20940
20970
21000
21030
21060
21090
21120
21150
21180
21210
21240
21270
21300
21330
21360
21390
21420
21450
21480
21510
21540
21570
21600
21630
21660
21690
21720
21750
21780
21810
21840
21870
21900
21930
21960
21990
22020
22050
22080
22110
22140
22170
22200
22230
22260
22290
22320
22350
22380
22410
22440
22470
22500
22530
22560
22590
22620
22650
22680
22710
22740
22770
22800
22830
22860
22890
22920
22950
22980
23010
23040
23070
23100
23130
23160
23190
23220
23250
23280
23310
23340
23370
23400
23430
23460
23490
23520
23550
23580
23610
23640
23670
23700
23730
23760
23790
23820
23850
23880
23910
23940
23970
24000
24030
24060
24090
24120
24150
24180
24210
24240
24270
24300
24330
24360
24390
24420
24450
24480
24510
24540
24570
24600
24630
24660
24690
24720
24750
24780
24810
24840
24870
24900
24930
24960
24990
25020
25050
25080
25110
25140
25170
25200
25230
25260
25290
25320
25350
25380
25410
25440
25470
25500
25530
25560
25590
25620
25650
25680
25710
25740
25770
25800
25830
25860
25890
25920
25950
25980
26010
26040
26070
26100
26130
26160
26190
26220
26250
26280
26310
26340
26370
26400
26430
26460
26490
26520
26550
26580
26610
26640
26670
26700
26730
26760
26790
26820
26850
26880
26910
26940
26970
27000
27030
27060
27090
27120
27150
27180
27210
27240
27270
27300
27330
27360
27390
27420
27450
27480
27510
27540
27570
27600
27630
27660
27690
27720
27750
27780
27810
27840

In [13]:
json_file_path = "old_cars_list.json"
with open(json_file_path, "w", encoding='utf-8') as json_file:
    json.dump(results, json_file, ensure_ascii=False, indent=4)

    print(f"The data has been successfully exported to {json_file_path}.")

The data has been successfully exported to old_cars_list.json.

In [1]:
import json
from urllib.request import urlopen,Request
from bs4 import BeautifulSoup
import ssl
import urllib
import re

def extract_info(url):
    
    # Ignore SSL certificate errors
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE

    req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})

    html = urlopen(req, context=ctx).read()
    soup = BeautifulSoup(html, "html.parser")
    
    marque_span = soup.find('span', class_='text_bold')
    price_div = soup.find('div', class_='color_primary text_bold price-block')
    detail_lines = soup.find_all('div', class_='detail_line')

    marque_span=marque_span.text.strip()
    marque=marque_span.split(' ')[0]
    model=marque_span.split(' ')[1]
    price = int(re.sub(r'\D', '', price_div.text.strip()))
    # Creating the dictionary
    car_info_dict = {
        'marque': marque,
        'model': model,  # You can set the model to None or any default value if not available in the HTML
        'price': price
    }

    # Iterate through detail_line divs and extract information
    for detail_line in detail_lines:
        key = detail_line.find('span', class_='col-md-6 col-xs-6').text.strip()
        value = detail_line.find('span', class_='text_bold').text.strip()
        car_info_dict[key] = value

    return car_info_dict

In [2]:
extract_info('https://www.moteur.ma/fr/voiture/achat-voiture-occasion/detail-annonce/434385/dacia-sandero-.html')

{'marque': 'DACIA',
 'model': 'Sandero',
 'price': 69000,
 'Kilométrage': '249 000',
 'Année': '2013',
 'Boite de vitesses': 'Manuelle',
 'Carburant': 'Diesel',
 'Date': '21-01-2024',
 'Puissance fiscale': '6',
 'Nombre de portes': '5',
 'Véhicule dédouané': '2013'}

In [3]:
file_path = 'old_cars_list.json'

# Read the JSON file
with open(file_path, 'r') as file:
    urls = json.load(file)

In [14]:
json_file_path = "old_cars.json"

for i in range (18695,len(urls)):
    car_info = extract_info(urls[i])
        
    # Write the result to the JSON file
    with open(json_file_path, "a", encoding='utf-8') as json_file:
        json.dump(car_info, json_file, ensure_ascii=False, indent=4)
        json_file.write(',\n')  # Add a newline between entries
    
    if i % 100 == 0:
        print(f"Processed {i} URLs")

print(f"The data has been successfully exported to {json_file_path}.")

Processed 18700 URLs
Processed 18800 URLs
Processed 18900 URLs
Processed 19000 URLs
Processed 19100 URLs
Processed 19200 URLs
Processed 19300 URLs
Processed 19400 URLs
Processed 19500 URLs
Processed 19600 URLs
Processed 19700 URLs
Processed 19800 URLs
Processed 19900 URLs
Processed 20000 URLs
Processed 20100 URLs
Processed 20200 URLs
Processed 20300 URLs
Processed 20400 URLs
Processed 20500 URLs
Processed 20600 URLs
Processed 20700 URLs
Processed 20800 URLs
Processed 20900 URLs
Processed 21000 URLs
Processed 21100 URLs
Processed 21200 URLs
Processed 21300 URLs
Processed 21400 URLs
Processed 21500 URLs
Processed 21600 URLs
Processed 21700 URLs
Processed 21800 URLs
Processed 21900 URLs
Processed 22000 URLs
Processed 22100 URLs
Processed 22200 URLs
Processed 22300 URLs
Processed 22400 URLs
Processed 22500 URLs
Processed 22600 URLs
Processed 22700 URLs
Processed 22800 URLs
Processed 22900 URLs
Processed 23000 URLs
Processed 23100 URLs
Processed 23200 URLs
Processed 23300 URLs
Processed 23400 URLs
Processed 23500 URLs
Processed 23600 URLs
Processed 23700 URLs
Processed 23800 URLs
Processed 23900 URLs
Processed 24000 URLs
Processed 24100 URLs
Processed 24200 URLs
Processed 24300 URLs
Processed 24400 URLs
Processed 24500 URLs
Processed 24600 URLs
Processed 24700 URLs
Processed 24800 URLs
Processed 24900 URLs
Processed 25000 URLs
Processed 25100 URLs
Processed 25200 URLs
Processed 25300 URLs
Processed 25400 URLs
Processed 25500 URLs
Processed 25600 URLs
Processed 25700 URLs
Processed 25800 URLs
Processed 25900 URLs
Processed 26000 URLs
Processed 26100 URLs
The data has been successfully exported to old_cars.json.

In [15]:
import json
import csv

# Assuming the JSON file is named 'old_cars.json'
json_file_path = 'old_cars.json'

# Read the JSON file
with open(json_file_path, 'r', encoding='utf-8') as json_file:
    cars_list = json.load(json_file)

# Specify the attributes to include in the CSV file
selected_attributes = ["marque", "model", "Puissance fiscale", "Carburant", "Année", "Boite de vitesses","price"]

# Specify the CSV file path
csv_file_path = "old_cars.csv"

# Write the header to the CSV file
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file:
    csv_writer = csv.DictWriter(csv_file, fieldnames=selected_attributes)
    csv_writer.writeheader()

    # Write each car's information to the CSV file
    for car_info in cars_list:
        selected_info = {attr: car_info.get(attr, "") for attr in selected_attributes}
        csv_writer.writerow(selected_info)

print(f"The data has been successfully exported to {csv_file_path}.")

The data has been successfully exported to old_cars.csv.

In [16]:
import pandas as pd

In [20]:
df=pd.read_csv('old_cars.csv')

In [21]:
df.head(25)

,marque,model,Puissance fiscale,Carburant,Année,Boite de vitesses,price
0,LAND-ROVER,Range,12.0,Diesel,2017,Automatique,490000
1,LAND-ROVER,Range,12.0,Diesel,2016,Automatique,355000
2,BMW,X5,8.0,Diesel,2016,Automatique,260000
3,LAND-ROVER,Range,8.0,Diesel,2018,Automatique,310000
4,MERCEDES,Classe,8.0,Diesel,2022,Automatique,820000
5,MERCEDES,Classe,8.0,Diesel,2019,Automatique,355000
6,HYUNDAI,Santa,9.0,Diesel,2020,Automatique,285000
7,MERCEDES,Gle,12.0,Diesel,2018,Automatique,339000
8,ALFA-ROMEO,Stelvio,9.0,Diesel,2019,Automatique,275000
9,JEEP,Renegade,6.0,Diesel,2022,Automatique,257000
10,RENAULT,Clio,6.0,Diesel,2020,Automatique,152000
11,LAND-ROVER,Range,8.0,Diesel,2018,Automatique,370000
12,BENTLEY,Continental,30.0,Essence,2017,Automatique,1100000
13,VOLKSWAGEN,Touareg,12.0,Diesel,2023,Automatique,480000
14,JEEP,Grand,12.0,Diesel,2017,Automatique,200000
15,BMW,Serie,12.0,Diesel,2017,Automatique,450000
16,AUDI,Q5,8.0,Diesel,2019,Automatique,440000
17,LAND-ROVER,Range,12.0,Diesel,2016,Automatique,365000
18,MERCEDES,Classe,9.0,Diesel,2004,Automatique,98000
19,MERCEDES,Classe,8.0,Diesel,2008,Automatique,137000
20,MERCEDES,Classe,11.0,Diesel,2006,Automatique,105000
21,MERCEDES,Classe,11.0,Diesel,2008,Automatique,108000
22,VOLKSWAGEN,Golf,8.0,Diesel,2022,Automatique,310000
23,HYUNDAI,Elantra,6.0,Diesel,2019,Manuelle,153000
24,BMW,Serie,8.0,Diesel,2015,Automatique,225000

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26133 entries, 0 to 26132
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   marque             26133 non-null  object
 1   model              26133 non-null  object
 2   Puissance fiscale  24172 non-null  float64
 3   Carburant          26133 non-null  object
 4   Année              26133 non-null  int64
 5   Boite de vitesses  25433 non-null  object
 6   price              26133 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 1.4+ MB

In [23]:
df['marque'] = df['marque'].str.lower()

In [26]:
df.head()

,marque,model,Puissance fiscale,Carburant,Année,Boite de vitesses,price
0,land-rover,Range,12.0,Diesel,2017,Automatique,490000
1,land-rover,Range,12.0,Diesel,2016,Automatique,355000
2,bmw,X5,8.0,Diesel,2016,Automatique,260000
3,land-rover,Range,8.0,Diesel,2018,Automatique,310000
4,mercedes,Classe,8.0,Diesel,2022,Automatique,820000

In [30]:
df['etat'] = 0
new_order = ["marque", "model", "Puissance fiscale", "Carburant", "Année", "Boite de vitesses","etat","price"]
df = df[new_order]
df.head()

,marque,model,Puissance fiscale,Carburant,Année,Boite de vitesses,etat,price
0,land-rover,Range,12.0,Diesel,2017,Automatique,0,490000
1,land-rover,Range,12.0,Diesel,2016,Automatique,0,355000
2,bmw,X5,8.0,Diesel,2016,Automatique,0,260000
3,land-rover,Range,8.0,Diesel,2018,Automatique,0,310000
4,mercedes,Classe,8.0,Diesel,2022,Automatique,0,820000

In [31]:
df.to_csv('u_old_cars.csv', index=False, encoding='utf-8')